### PR TITLE
Use declarativeNetRequest to block embeds

### PR DESCRIPTION
**Pull request by hymccord**
- Unify to one extension
- Use declaritiveNetRequest to block embeds

[DNR](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/declarativeNetRequest) is the proper way to block scripts from loading in MV3 extensions. It also allows going to a unified code base since both support MV3 and DNR now.

MV3 extensions in Firefox don't run content_scripts by default it requires the user to agree to per site permissions. However, since this is only for cosmetic changes it's not that big of a deal.

### CODE REVIEW

**Comment by hymccord** [comment]
Any reason you are using a blacklist? It's easy to swap the request blocking to `<all_urls>` which will block the embeds everywhere.

**Comment by LogicalSoIutions** [comment]
Never built an extension before - did some quick skimming and tried some stuff and just sent what worked.

Will probably merge this tomorrow/Thursday after testing. Thank you!

**Comment by hymccord** [comment]
No worries. You have to start somewhere!  

I can also help automate the submission to the stores if you would like that. I do that for my other projects.

**Comment by LogicalSoIutions** [comment]
Automate to the store? That does sound interesting!

Just tested - all is good. Thank you!

**Comment by LogicalSoIutions** [comment]
https://i.imgur.com/ZDjOTTC.png

Guess I should have made sure it uploaded without issue ~

**Comment by LogicalSoIutions** [comment]
This manifest errors for Firefox now? That is why I had initially split them up.

**Comment by hymccord** [comment]
That's strange because I loaded it in both browsers to make sure merging
the manifests was fine. The store may have different requirements.

**Comment by hymccord** [comment]
You can add it under the key ` browser_specific_settings.gecko.id`. Chrome
will be fine with it.

Example
```
 "browser_specific_settings": {
        "gecko": {
            "id": "{<extension_guid>}"
        }
    }
```

**Pull request merged**
